name: JDBC Driver

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - flight-jdbc-driver-release
  pull_request:
    branches:
      - flight-jdbc-driver-release
jobs:
  build:
    # Execute on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Build
      run: mvn -B verify --file java/flight/flight-jdbc-driver/pom.xml
    - name: Copy Build
      run: |
        mkdir jarfile
        cp target/*.jar jarfile
    - name: Upload Build
      uses: actions/upload-artifact@v1
      with:
        name: jarfile
        path: jarfile
